## Working with types:
### * Reading values and printing data
### * int and float variable types  and math operations
### * boolean variables and operations
### * Working with strings and string operations, slicing, find

# Problem 1
Replace the names of your homework team members

In [ ]:
first_team_member_name = "John Doe 1"
second_team_member_name = "John Doe 2"

In [ ]:
print("Our team member are", first_team_member_name," and ",second_team_member_name)

Our team member are John Doe 1  and  John Doe 2

# Problem 2
Print the the type of the variable named "first_team_member_name"

# Problem 3
Print the length of the vriable named "second_team_member_name"

# Problem 4
Print the first, the last and the third characters of the variable named "second_team_member_name"

# Problem 5
Print the family named contained on the variable named "first_team_member_name"
Hint: use slicing [X:Y] calculating manually the start position of the family name inside the string

#Problem 6
Enter two numbers a and b. Print True is a >= b. Otherwise False.
Example: Input: 3,4 -> Output: 3  >= 4 : False

In [ ]:
a = input("Enter number a:")

Enter number a:3

In [ ]:
b = input("Enter number b:")

Enter number b:4

#Problem 7
Enter a number a. Print if a is multiple of 3 and/or multiple of 5 and/or multiple of 15.
Example: Input: a=30 -> Output: Number  30  is multiple of 3? True  - is multiple of 5? True - is multiple of 15? True

In [ ]:
a = input("Enter number a")

Enter number a30

#Problem 8:
Enter an amount in dolars and the current exchange rate dolar to shequel.
The program should print the input variables and the current value on shequels.
Example: Input: dolar_amount=45, exchange_rate=3.22 -> Output: Changing  45  dolars to shequels using an exchange rate of  3.22  you get  144.9 shequels

In [ ]:
amount_in_dollars = input("Enter amount in dollars:")

Enter amount in dollars:45

#Problem 9
Write a Python program that accepts an integer digit (n) and computes the value of n+nn+nnn
Example: Input: n = 1 -> Result: 123 (1+11+111)

In [ ]:
n = input("Enter a digit:")

Enter a digit:1

In [ ]:
n = int(n)

#Problem 10
Enter a non-empty string S and a non-negative number N. Write a Python program to get a string which is N copies of a given string S.
Example: Input: Israel, 4 Output: IsraelIsraelIsraelIsrael

In [ ]:
my_string = input("Enter a string:")

Enter a string:Israel

In [ ]:
repetitions = input("Enter number of repetitions:")

Enter number of repetitions:4

#Problem 11
Print 8 lines compound of 8 '$; signs

#Problem 12
Enter three strings with your Surname, Family name and full address. Print your names in reverse order. Print also True if 7 or Hertlz is part of your address; otherwise print False

Example:Input: Marcelo, Feighelstein, Hertzl 37 Output: Welcome  Feighelstein Marcelo . Your address is  Hertzl 37 . Are you lucky? True

In [ ]:
surname = input("Enter your name:")

Enter your name:Marcelo

In [ ]:
family_name = input("Enter your Family name:")

Enter your Family name:Feighelstein

In [ ]:
address = input("Enter your address:")

Enter your address:Hertlz 37

#Problem 13
Enter a string of at least 10 chanracters. Print the first character, the last character, the string starting from the 4th character until the end of the string, the last 5 characters, and the string between the 2rd and 5th characters.
Example: Input: Games of Thrones Outputs: G,s,es of Thornes, rones, ame

In [ ]:
my_string = input("Enter a string (at least 10 characters):")

Enter a string (at least 10 characters):Games of Thrones

#Problem 14
Write a Python program to accept a filename from the user and print the extension of that file
Example: Input: Image.jpg -> Output:jpg
Assumptiom: file name has an unique "." character

In [ ]:
my_filename = input("Enter a filename:")

Enter a filename:Image.jpg